#! /bin/bash

uri=''
image='image.png'
sleeptime=20
display=99
width=1280
height=720

if ! options=$(getopt -u -o u:i:s:d:w:h: -l uri:,image:,sleep-time:,display:,width:,height:, -- "$@")
then
	exit 1
fi

set -- $options
while [ $# -gt 0 ] ; do
	case $1 in
	-u|--uri) uri="$2" ; shift;;
	-i|--image) image="$2" ; shift;;
	-s|--sleep-time) sleeptime="$2" ; shift;;
	-d|--display) display="$2" ; shift;;
	-w|--width) width="$2" ; shift;;
	-h|--height) height="$2" ; shift;;
	(--) shift; break;;
	(-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
	(*) break;;
	esac
	shift
done

if [ -c $image ] ; then
	rm $image
fi

# start xvfb
Xvfb :$display -screen 1 "$width"x"$height"x24 &
xvfbPID=$!

# start chrome
DISPLAY=:$display.1 webkitRender.py $uri &

# capture image
sleep $sleeptime
DISPLAY=:$display.1 import -window root $image

# clean up when done
kill -9 $xvfbPID
killall webkitRender.py
